library(ggplot2)
library(cowplot)
theme_set(theme_bw())


# Multiple Plots ----------------------------------------------------------

p1 <- a

p2 <- a

p3 <- a


ggdraw() + 
  draw_plot(p1, 0, 0, 0.7, 1) +  # 在母图左半部，占图比例1/2  (x, y, width, height)
  draw_plot(p2, 0.7, 0, 0.3, 0.5) + 
  draw_plot(p3, 0.7, 0.5, 0.3, 0.5) + 
  draw_plot_label(c("A", "B", "C"), c(0, 0.7, 0.7), c(1, 1, 0.5), size = 10)  # 标签






# Fig 1 [15:8] -------------------------------------------------------------

ggdraw() + 
  draw_plot(p1, 0, 0, 0.7, 1) +  # 在母图左半部，占图比例1/2  (x, y, width, height)
  draw_plot(p2, 0.7, 0.5, 0.3, 0.5) + 
  draw_plot(p3, 0.7, 0, 0.3, 0.5) + 
  draw_label("generated by \n Generalized Linear Model (GLM) \n ----- ----- ----- -----", x = 0.59, y = 0.2, hjust = 0.5, vjust = 0, size = 12, lineheight = 1.5) + 
  draw_label("formula: Response ~ StimNo + Session \n (1 = [l], 0 = [n])", x = 0.59, y = 0.12, hjust = 0.5, vjust = 0, size = 11, lineheight = 1.5) + 
  draw_plot_label(c("A", "B", "C"), c(0, 0.7, 0.7), c(1, 1, 0.5), size = 10)  # 标签




# Fig 2 [15:9] -------------------------------------------------------------------

ggdraw() + 
  draw_plot(p1, 0, 0, 0.5, 1) +  # 在母图左半部，占图比例1/2  (x, y, width, height)
  draw_plot(p2, 0.5, 0.6, 0.5, 0.4) + 
  draw_plot(p3, 0.55, 0, 0.4, 0.6) + 
  draw_plot_label(c("A", "B", "C"), c(0, 0.5, 0.5), c(1, 1, 0.6), size = 10)  # 标签



